# Generated by Django 5.0.6 on 2024-06-11 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=50, verbose_name='Product Name')),
                ('photo', models.CharField(max_length=20, null=True, verbose_name='Photo')),
                ('price', models.FloatField()),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('category_code', models.CharField(max_length=10, verbose_name='Category Code')),
                ('category_name', models.CharField(max_length=50, verbose_name='Category Name')),
                ('subcategory_code', models.CharField(max_length=20, verbose_name='Subcategory Code')),
                ('subcategory_name', models.CharField(max_length=20, verbose_name='Subcategory')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Full Name')),
                ('username', models.CharField(max_length=50, null=True, unique=True, verbose_name='Username')),
                ('telegram_id', models.PositiveIntegerField(unique=True, verbose_name='Telegram ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
