# Generated by Django 5.0.6 on 2024-06-11 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_category_order'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='products',
            table='products',
        ),
        migrations.AlterModelTable(
            name='users',
            table='users',
        ),
    ]
